### ISSUE TITLE
Balance analytics chart more data points

### ISSUE THREAD

**Issue by armandasalmd** [armandasalmd/money-can-fly#71]
**Task:** Update Balance analysis section in dashboard page

### The new look prototype
![image](https://github.com/armandasalmd/money-can-fly/assets/17089888/adc3d0de-aa00-4a6e-aae9-1edb4c2c4e33)

### Features
- [x] Refactor backend logic to enable new features (i.e. reading from database algorithm will completely change) 
  - [x] Optimize db reads and /dashboard load time. Benchmark request ms
- [x] Card action buttons (icons + tooltips)
  - [x] Refresh
  - [x] Calibrate
  - [x] Fullscreen
  - [x] Settings
- [x] New chart implementation
  - [x] Y-axis labels should format as default currency labels
  - [x] Chart should no longer display fixed amount of datapoints (Remove "Date breakpoint count" setting)
  - [x] Investment dataset should not be displayed on first page load by default (unless setting contradicts)
- [x] Add balance analysis settings as a new drawer. Add following settings
  - [x] Forecast pivot value (old setting) - general options section
  - [x] Forecast pivot date (old setting) - general options section
  - [x] Hide investments dataset on load - general options section
  - [x] Dataset color options section: "Total worth color", "Prediction color", "Investment color"
  - [x] Default date range options section (default: current month)
- [x] Refactor card footer:
  - [x] Date range selector should remain
  - [x] Forward, Backbards buttons should wrap around date range inputs and +- 1 month

**Comment by armandasalmd** [comment]
10 sample request to /dashboard/displayModel results in avg. 327ms before my changes. Later compare it with this number. Should be same or less

**Comment by armandasalmd** [comment]
Created a benchmark page with various cases. Benchmarks before changes:
![image](https://github.com/armandasalmd/money-can-fly/assets/17089888/5344cb83-5e3d-4331-9f82-d61d55e4a0a7)

**Comment by armandasalmd** [comment]
- Applied chunking in JS - date range is split into 600 chunks and grouped items are concatinated.
- Reduced fetched amount count by ~50% by applying simple $group technique. It concatinates close in time and same currency results on database

Results compared to original achieves around same `ms`. But new `7.89 ms/Kb` rating is better than previous `8.77 ms/Kb`. Thats **11.15%** improvement

![State2_Performance_New__Aggregate](https://github.com/armandasalmd/money-can-fly/assets/17089888/254336cd-06df-49ab-b8a7-7e934c9f9822)

**Comment by armandasalmd** [comment]
Stage 3. Did some more refactorings. Mainly removed unnecesarily investment full model return which was adding a lot to bandwith. 
- New changes will provide more accurate balance chart; 
- Shows 5 times less bandwith
- Overall 7.5% performance improvement
- Worse ms/kb rate. 36.5. As overall performance is better, we just send less unused data, its counted as positive

![image](https://github.com/armandasalmd/money-can-fly/assets/17089888/41dc89b4-9c7c-47a6-9d05-7dca04a35da4)

**Comment by armandasalmd** [comment]
POC benchmarks are above. Those were done in UK closer to db (in Ireland). Benchmarks after final POC implementation in Lithuania are acceptable (average less than 300ms):
![image](https://github.com/armandasalmd/money-can-fly/assets/17089888/0ec1ebcb-4f24-4d11-ba20-0a0e415f6623)
